name: GitHub Pages

on:
  push:
  pull_request:
  schedule:
          # Runs everyday at 8:00 AM
          - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo -F --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          EXTERNAL_REPOSITORY: ggcso/ggcso.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public